-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 08:31:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetimmotrad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetimmotrad` ;

-- -----------------------------------------------------
-- Schema projetimmotrad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetimmotrad` DEFAULT CHARACTER SET utf8 ;
USE `projetimmotrad` ;

-- -----------------------------------------------------
-- Table `projetimmotrad`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`agence` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`agence` (
  `idagence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(145) NULL,
  `adresseAgence` VARCHAR(145) NULL,
  `numRueAgence` VARCHAR(15) NULL,
  `cpAgence` VARCHAR(10) NULL,
  `villeAgence` VARCHAR(145) NULL,
  PRIMARY KEY (`idagence`),
  UNIQUE INDEX `idagence_UNIQUE` (`idagence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`client` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(95) NULL,
  `prenomClient` VARCHAR(145) NULL,
  `numRueClient` VARCHAR(10) NULL,
  `nomRueClient` VARCHAR(245) NULL,
  `cpClient` VARCHAR(10) NULL,
  `villeClient` VARCHAR(145) NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`option` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`option` (
  `idoption` INT NOT NULL AUTO_INCREMENT,
  `nomOption` VARCHAR(145) NULL,
  PRIMARY KEY (`idoption`),
  UNIQUE INDEX `idoption_UNIQUE` (`idoption` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`bien` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`bien` (
  `idbien` INT NOT NULL AUTO_INCREMENT,
  `nomBien` VARCHAR(45) NULL,
  `prixBien` VARCHAR(45) NULL,
  `nbPiece` VARCHAR(45) NULL,
  `surfaceMaison` VARCHAR(45) NULL,
  `surfaceTerrain` VARCHAR(45) NULL,
  `valeurCommission` VARCHAR(45) NULL,
  `numRueBien` VARCHAR(15) NULL,
  `nomRueBien` VARCHAR(45) NULL,
  `cpBien` VARCHAR(15) NULL,
  `villeBien` VARCHAR(145) NULL,
  `option_idoption` INT NOT NULL,
  `agence_idagence` INT NOT NULL,
  PRIMARY KEY (`idbien`),
  UNIQUE INDEX `idbien_UNIQUE` (`idbien` ASC),
  INDEX `fk_bien_option_idx` (`option_idoption` ASC),
  INDEX `fk_bien_agence1_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_bien_option`
    FOREIGN KEY (`option_idoption`)
    REFERENCES `projetimmotrad`.`option` (`idoption`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bien_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `projetimmotrad`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`achat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`achat` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`achat` (
  `bien_idbien` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  `dateAchat` DATETIME NULL,
  `datePaiment` DATETIME NULL,
  PRIMARY KEY (`bien_idbien`, `client_idclient`),
  INDEX `fk_bien_has_client_client1_idx` (`client_idclient` ASC),
  INDEX `fk_bien_has_client_bien1_idx` (`bien_idbien` ASC),
  CONSTRAINT `fk_bien_has_client_bien1`
    FOREIGN KEY (`bien_idbien`)
    REFERENCES `projetimmotrad`.`bien` (`idbien`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bien_has_client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `projetimmotrad`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
