-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 10:10:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`adresse` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`adresse` (
  `idadresse` INT(11) NOT NULL,
  `adresse` VARCHAR(250) NULL DEFAULT NULL,
  `code_postal` VARCHAR(6) NULL DEFAULT NULL,
  `ville` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idadresse`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `default_schema`.`race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`race` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`race` (
  `idrace` INT(11) NOT NULL,
  `nom_race` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idrace`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `default_schema`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`animals` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`animals` (
  `idAnimals` INT(11) NOT NULL,
  `nom_animal` VARCHAR(45) NULL DEFAULT NULL,
  `date_naissance` DATE NULL DEFAULT NULL,
  `race_idrace` INT(11) NOT NULL,
  PRIMARY KEY (`idAnimals`),
  INDEX `fk_animals_race1_idx` (`race_idrace` ASC),
  CONSTRAINT `fk_animals_race1`
    FOREIGN KEY (`race_idrace`)
    REFERENCES `default_schema`.`race` (`idrace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `default_schema`.`proprios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`proprios` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`proprios` (
  `idProprios` INT(11) NOT NULL,
  `nom_proprio` VARCHAR(45) NULL DEFAULT NULL,
  `prenom_proprio` VARCHAR(45) NULL DEFAULT NULL,
  `adresse_idadresse` INT(11) NOT NULL,
  `animals_idAnimals` INT(11) NOT NULL,
  PRIMARY KEY (`idProprios`),
  INDEX `fk_proprios_adresse_idx` (`adresse_idadresse` ASC),
  INDEX `fk_proprios_animals1_idx` (`animals_idAnimals` ASC),
  CONSTRAINT `fk_proprios_adresse`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `default_schema`.`adresse` (`idadresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proprios_animals1`
    FOREIGN KEY (`animals_idAnimals`)
    REFERENCES `default_schema`.`animals` (`idAnimals`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
