-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 14:21:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetimmotrad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetimmotrad` ;

-- -----------------------------------------------------
-- Schema projetimmotrad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetimmotrad` DEFAULT CHARACTER SET utf8 ;
USE `projetimmotrad` ;

-- -----------------------------------------------------
-- Table `projetimmotrad`.`Options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`Options` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`Options` (
  `idOptions` INT NOT NULL AUTO_INCREMENT,
  `nomOption` VARCHAR(245) NULL,
  `quantite` INT NULL DEFAULT 1,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idOptions`),
  UNIQUE INDEX `idOptions_UNIQUE` (`idOptions` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`Agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`Agence` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`Agence` (
  `idAgence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(145) NULL,
  `numRueAgence` VARCHAR(10) NULL,
  `nomRueAgence` VARCHAR(245) NULL,
  `cpAgence` VARCHAR(10) NULL,
  `villeAgence` VARCHAR(245) NULL,
  `phoneAgence` VARCHAR(15) NULL,
  `emailAgence` VARCHAR(245) NULL,
  PRIMARY KEY (`idAgence`),
  UNIQUE INDEX `idAgence_UNIQUE` (`idAgence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmotrad`.`Bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmotrad`.`Bien` ;

CREATE TABLE IF NOT EXISTS `projetimmotrad`.`Bien` (
  `idBien` INT NOT NULL AUTO_INCREMENT,
  `nomBine` VARCHAR(245) NULL,
  `prixBien` DECIMAL(10,2) NULL,
  `numAdresseBien` VARCHAR(15) NULL,
  `nomAdresseBine` VARCHAR(45) NULL,
  `cpBien` VARCHAR(10) NULL,
  `villeBien` VARCHAR(45) NULL,
  `commissionBine` DECIMAL(10,2) NULL,
  `photoBien` VARCHAR(145) NULL,
  `statut` TINYINT NULL,
  `surfaceBien` INT NULL,
  `sufaceTerrain` INT NULL,
  `Options_idOptions` INT NOT NULL,
  `Agence_idAgence` INT NOT NULL,
  PRIMARY KEY (`idBien`),
  UNIQUE INDEX `idBien_UNIQUE` (`idBien` ASC),
  INDEX `fk_Bien_Options_idx` (`Options_idOptions` ASC),
  INDEX `fk_Bien_Agence1_idx` (`Agence_idAgence` ASC),
  CONSTRAINT `fk_Bien_Options`
    FOREIGN KEY (`Options_idOptions`)
    REFERENCES `projetimmotrad`.`Options` (`idOptions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Bien_Agence1`
    FOREIGN KEY (`Agence_idAgence`)
    REFERENCES `projetimmotrad`.`Agence` (`idAgence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
